{
    "0": {
        "id": "zknhppycckbkb",
        "name": "Monthly Meetup",
        "status": "upcoming",
        "local_date": "2021-07-07",
        "local_time": "19:00",
        "yes_rsvp_count": 6,
        "venue": {
            "id": 25610164,
            "name": "Oath",
            "lat": 39.2816162109375,
            "lon": -76.58175659179688,
            "repinned": false,
            "address_1": "2400 Boston Street Suite 300",
            "city": "Baltimore",
            "country": "us",
            "localized_country_name": "USA",
            "zip": "",
            "state": "MD"
        },
        "is_online_event": false,
        "group": {
            "created": 1428329232000,
            "name": "charmCityJs",
            "id": 18535249,
            "join_mode": "open",
            "lat": 39.290000915527344,
            "lon": -76.62000274658203,
            "urlname": "charmcityjs",
            "who": "JavaScripters",
            "localized_location": "Baltimore, MD",
            "state": "MD",
            "country": "us",
            "region": "en_US",
            "timezone": "US/Eastern"
            },
        "link": "https://www.meetup.com/charmcityjs/events/zknhppycckbkb/",
        "description": "<p>Always the first Wednesday of the month at 7pm!</p> <p>Speakers this month:</p> <p>• Speaker #1 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #2 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #3 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>We want to hear from you! If you have an idea for a talk, submit a quick description through our github page (<a href="https://github.com/charmCityJs/talks" class="linkified">https://github.com/charmCityJs/talks</a>)! We especially love first time presenters and new perspectives. Don't hesitate to contact us directly with questions.</p> <p>We're dedicated to providing a harassment-free meetup experience for everyone. Our policy is here (<a href="http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy" class="linkified">http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy</a>).</p> ",
        "how_to_find_us": "Check here or twitter: https://twitter.com/charmcityjs",
        "visibility": "public",
        "member_pay_fee": false
        },
        
    "1": {
        "id": "zknhppycclbgb",
        "name": "Monthly Meetup",
        "status": "upcoming",
        "local_date": "2021-08-04",
        "local_time": "19:00",
        "yes_rsvp_count": 0,
        "venue": {
            "id": 25610164,
            "name": "Oath",
            "lat": 39.2816162109375,
            "lon": -76.58175659179688,
            "repinned": false,
            "address_1": "2400 Boston Street Suite 300",
            "city":"Baltimore",
            "country": "us",
            "localized_country_name": "USA",
            "zip": "",
            "state": "MD"
        },
        "is_online_event": false,
        "group": {
        "created": 1428329232000,
        "name": "charmCityJs",
        "id": 18535249,
        "join_mode": "open",
        "lat": 39.290000915527344,
        "lon": -76.62000274658203,
        "urlname": "charmcityjs",
        "who": "JavaScripters",
        "localized_location": "Baltimore, MD",
        "state": "MD",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Eastern"
        },
        "link": "https://www.meetup.com/charmcityjs/events/zknhppycclbgb/",
        "description": "<p>Always the first Wednesday of the month at 7pm!</p> <p>Speakers this month:</p> <p>• Speaker #1 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #2 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #3 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>We want to hear from you! If you have an idea for a talk, submit a quick description through our github page (<a href="https://github.com/charmCityJs/talks" class="linkified">https://github.com/charmCityJs/talks</a>)! We especially love first time presenters and new perspectives. Don't hesitate to contact us directly with questions.</p> <p>We're dedicated to providing a harassment-free meetup experience for everyone. Our policy is here (<a href="http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy" class="linkified">http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy</a>).</p> ",
        "how_to_find_us": "Check here or twitter: https://twitter.com/charmcityjs",
        "visibility": "public",
        "member_pay_fee": false
    },

    "2": {
        "id": "zknhppyccmbcb",
        "name": "Monthly Meetup",
        "status": "upcoming",
        "local_date": "2021-09-01",
        "local_time": "19:00",
        "yes_rsvp_count": 0,
        "venue": {
            "id": 25610164,
            "name": "Oath",
            "lat": 39.2816162109375,
            "lon": -76.58175659179688,
            "repinned": false,
            "address_1": "2400 Boston Street Suite 300",
            "city": "Baltimore",
            "country": "us",
            "localized_country_name": "USA",
            "zip": "",
            "state": "MD"
        },
        "is_online_event": false,
        "group": {
            "created": 1428329232000,
            "name": "charmCityJs",
            "id": 18535249,
            "join_mode": "open",
            "lat": 39.290000915527344,
            "lon": -76.62000274658203,
            "urlname": "charmcityjs",
            "who": "JavaScripters",
            "localized_location": "Baltimore, MD",
            "state": "MD",
            "country": "us",
            "region": "en_US",
            "timezone": "US/Eastern"
        },
        "link": "https://www.meetup.com/charmcityjs/events/zknhppyccmbcb/",
        "description": "<p>Always the first Wednesday of the month at 7pm!</p> <p>Speakers this month:</p> <p>• Speaker #1 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #2 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #3 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>We want to hear from you! If you have an idea for a talk, submit a quick description through our github page (<a href="https://github.com/charmCityJs/talks" class="linkified">https://github.com/charmCityJs/talks</a>)! We especially love first time presenters and new perspectives. Don't hesitate to contact us directly with questions.</p> <p>We're dedicated to providing a harassment-free meetup experience for everyone. Our policy is here (<a href="http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy" class="linkified">http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy</a>).</p> ",
        "how_to_find_us": "Check here or twitter: https://twitter.com/charmcityjs",
        "visibility": "public",
        "member_pay_fee": false
    },

    "3": {
        "id": "zknhppyccnbjb",
        "name": "Monthly Meetup",
        "status": "upcoming",
        "local_date": "2021-10-06",
        "local_time": "19:00",
        "yes_rsvp_count": 0,
        "venue": {
            "id": 25610164,
            "name": "Oath",
            "lat": 39.2816162109375,
            "lon": -76.58175659179688,
            "repinned": false,
            "address_1": "2400 Boston Street Suite 300",
            "city": "Baltimore",
            "country": "us",
            "localized_country_name": "USA",
            "zip": "",
            "state": "MD"
        },
        "is_online_event": false,
        "group": {
            "created": 1428329232000,
            "name": "charmCityJs",
            "id": 18535249,
            "join_mode": "open",
            "lat": 39.290000915527344,
            "lon": -76.62000274658203,
            "urlname": "charmcityjs",
            "who": "JavaScripters",
            "localized_location": "Baltimore, MD",
            "state": "MD",
            "country": "us",
            "region": "en_US",
            "timezone": "US/Eastern"
        },
        "link": "https://www.meetup.com/charmcityjs/events/zknhppyccnbjb/",
        "description": "<p>Always the first Wednesday of the month at 7pm!</p> <p>Speakers this month:</p> <p>• Speaker #1 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #2 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #3 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>We want to hear from you! If you have an idea for a talk, submit a quick description through our github page (<a href="https://github.com/charmCityJs/talks" class="linkified">https://github.com/charmCityJs/talks</a>)! We especially love first time presenters and new perspectives. Don't hesitate to contact us directly with questions.</p> <p>We're dedicated to providing a harassment-free meetup experience for everyone. Our policy is here (<a href="http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy" class="linkified">http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy</a>).</p> ",
        "how_to_find_us": "Check here or twitter: https://twitter.com/charmcityjs",
        "visibility": "public",
        "member_pay_fee": false
    },

    "4": {
        "id": "zknhppyccpbfb",
        "name": "Monthly Meetup",
        "status": "upcoming",
        "local_date": "2021-11-03",
        "local_time": "19:00",
        "yes_rsvp_count": 0,
        "venue": {
            "id": 25610164,
            "name": "Oath",
            "lat": 39.2816162109375,
            "lon": -76.58175659179688,
            "repinned": false,
            "address_1": "2400 Boston Street Suite 300",
            "city": "Baltimore",
            "country": "us",
            "localized_country_name": "USA",
            "zip": "",
            "state": "MD"
        },
        "is_online_event": false,
        "group": {
            "created": 1428329232000,
            "name": "charmCityJs",
            "id": 18535249,
            "join_mode": "open",
            "lat": 39.290000915527344,
            "lon": -76.62000274658203,
            "urlname": "charmcityjs",
            "who": "JavaScripters",
            "localized_location": "Baltimore, MD",
            "state": "MD",
            "country": "us",
            "region": "en_US",
            "timezone": "US/Eastern"
        },
        "link": "https://www.meetup.com/charmcityjs/events/zknhppyccpbfb/",
        "description": "<p>Always the first Wednesday of the month at 7pm!</p> <p>Speakers this month:</p> <p>• Speaker #1 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #2 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #3 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>We want to hear from you! If you have an idea for a talk, submit a quick description through our github page (<a href="https://github.com/charmCityJs/talks" class="linkified">https://github.com/charmCityJs/talks</a>)! We especially love first time presenters and new perspectives. Don't hesitate to contact us directly with questions.</p> <p>We're dedicated to providing a harassment-free meetup experience for everyone. Our policy is here (<a href="http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy" class="linkified">http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy</a>).</p> ",
        "how_to_find_us": "Check here or twitter: https://twitter.com/charmcityjs",
        "visibility": "public",
        "member_pay_fee": false
    },

    "5": {
        "id": "zknhppyccqbcb",
        "name": "Monthly Meetup",
        "status": "upcoming",
        "local_date": "2021-12-01",
        "local_time": "19:00",
        "yes_rsvp_count": 0,
        "venue": {
            "id": 25610164,
            "name": "Oath",
            "lat": 39.2816162109375,
            "lon": -76.58175659179688,
            "repinned": false,
            "address_1": "2400 Boston Street Suite 300",
            "city": "Baltimore",
            "country": "us",
            "localized_country_name": "USA",
            "zip": "",
            "state": "MD"
        },
        "is_online_event": false,
        "group": {
            "created": 1428329232000,
            "name": "charmCityJs",
            "id": 18535249,
            "join_mode": "open",
            "lat": 39.290000915527344,
            "lon": -76.62000274658203,
            "urlname": "charmcityjs",
            "who": "JavaScripters",
            "localized_location": "Baltimore, MD",
            "state": "MD",
            "country": "us",
            "region": "en_US",
            "timezone": "US/Eastern"
        },
        "link": "https://www.meetup.com/charmcityjs/events/zknhppyccqbcb/",
        "description": "<p>Always the first Wednesday of the month at 7pm!</p> <p>Speakers this month:</p> <p>• Speaker #1 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #2 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>• Speaker #3 - TBA (submit a talk! (<a href="https://github.com/charmcityjs/talks" class="linkified">https://github.com/charmcityjs/talks</a>))</p> <p>We want to hear from you! If you have an idea for a talk, submit a quick description through our github page (<a href="https://github.com/charmCityJs/talks" class="linkified">https://github.com/charmCityJs/talks</a>)! We especially love first time presenters and new perspectives. Don't hesitate to contact us directly with questions.</p> <p>We're dedicated to providing a harassment-free meetup experience for everyone. Our policy is here (<a href="http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy" class="linkified">http://www.meetup.com/charmcityjs/pages/charmCityJS_Anti-Harassment_Policy</a>).</p> ",
        "how_to_find_us": "Check here or twitter: https://twitter.com/charmcityjs",
        "visibility": "public",
        "member_pay_fee": false
        }
    }
    